volumes:
  runs:

services:
  yolo:
    build:
      context: ./YOLO
      dockerfile: Dockerfile
    container_name: yolo-container
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    shm_size: '32gb'
    volumes:
      - runs:/app/runs
    ports:
      - "6006:6006"
